Add Crud for Users
wolox-training/jc-java pull request #10
Opened 2019-10-30 13:09 UTC by Casanova569

**Summary**
The card is considered approved if the UsersController has everything requested (CRUD methods), compiles and the application lifts without errors.

**Trello Card**
[Crear user controller con las operaciones crud de user](https://trello.com/c/HjGx87GA/21-crear-user-controller-con-las-operaciones-crud-de-user)

2019-11-01 17:04 UTC, Jimenarosello requested changes
Check out my comments :)

2019-11-01 17:04 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/UsersController.java
> +public class UsersController {
Remember to use the mapping for this API :) (`@RequestMapping("/users")`)  
And don't forget the `@RestController` annotation

2019-11-01 17:04 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/UsersController.java
> +	@GetMapping("/list")
As a convention for RESTful APIs, we use the following conventions for our endpoints: 
`GET "/"` returns the list of all resources (in this case, users) 
`GET "/{id}"` returns one specific resource 
`POST "/"` creates a resource 
`PUT "/{id}"` updates a specific resource 
`DELETE "/{id}"` deletes a specific resource 
So in order to follow this convention, the mapping in this case would be simply "/" 😃

2019-11-01 17:04 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/UsersController.java
> +		return usersRepository.save(user);
A good practice could be to validate that the user doesn't already exist :)

2019-11-01 17:04 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/UsersController.java
> +		if (user.getId() != id) {
If you use `Long` for the id (the class, not the primitive type `long`), you should use `.equals()` instead of `==` for comparisons. 
`==` compares the addresses whereas `.equals()` compares the contents. Check this out for further examples https://www.geeksforgeeks.org/difference-equals-method-java/ 😄

2019-11-01 17:04 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/UsersController.java
> +			throw new UsersNotFoundException("User id not found", new Exception());
Maybe throw a `UserMismatchException` instead :)

2019-11-01 17:04 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/UsersController.java
> +	@DeleteMapping("/{id}")
Be careful as this endpoint is duplicated, the endpoint for deleting a book from the user's collection should be something like `@DeleteMapping("/{id}/{bookId}")` 😅

2019-11-07 15:20 UTC, Jimenarosello requested changes

2019-11-07 15:20 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/BookController.java
> +			throw new BookIdMismatchException("Book already created", new Exception());
Maybe add a specific Exception for this case, BookAlreadyExistsException :) and the same goes for Users

2019-11-13 13:19 UTC, Jimenarosello requested changes
Just one detail and it should be ready :)

2019-11-13 13:19 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/BookController.java
> +		if(bookRepository.findById(book.getId()) == null)
did you remove the optional check for a specific reason? We tend to avoid nullchecks using optional when possible :)

2019-11-14 15:14 UTC, Casanova569 commented on src/main/java/wolox/training/controllers/BookController.java
> +		if(bookRepository.findById(book.getId()) == null)
Fixed in [Add Tests](https://github.com/wolox-training/jc-java/pull/13)

2019-11-19 14:00 UTC, rodrigofranc approved these changes

2019-11-21 13:36 UTC, Jimenarosello approved these changes
😄  sorry for the delay

2019-11-21 13:37 UTC, merged