Swagger
wolox-training/jc-java pull request #11
Opened 2019-10-30 17:04 UTC by Casanova569

**Summary**
Implement swagger in at least one controller and one model.

**Trello Card**
[Swagger](https://trello.com/c/1BJwnFjo/40-swagger)

2019-11-01 17:32 UTC, Jimenarosello requested changes
Just a small correction :) 

Also, check out this document with more annotations that you can use to make your swagger documentation more complete 😄 https://dzone.com/articles/spring-boot-2-restful-api-documentation-with-swagg 

PS: I noticed you're using tabs for indentation, as a convention we use 4 spaces instead :) 
You can configure this in the IDE so that you don't have to manually write 4 spaces, let me know if you need help finding that option! Don't change it now as it will cause differences in the repository, but keep it in mind for future projects 😊

2019-11-01 17:32 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/BookController.java
>  	@GetMapping("/list")
Sorry I didn't notice this in previous PRs 😓the endpoint should be simply "/" :) 
 Check out the comment about RESTful APIs naming conventions that I wrote in the UserController PR  😄

2019-11-07 15:26 UTC, Jimenarosello submitted a review, later dismissed

2019-11-19 14:21 UTC, rodrigofranc approved these changes

2019-11-21 13:40 UTC, Jimenarosello approved these changes

2019-11-21 13:41 UTC, merged