Add Validations to Setters
wolox-training/jc-java pull request #12
Opened 2019-10-30 18:52 UTC by Casanova569

**Summary**
The card it is considered approved if the pre-conditions are placed and the app compile.

**Trello Card**
[Agregar validaciones de precondiciones a los setters](https://trello.com/c/CAyeDWLO/29-agregar-validaci%C3%B3n-de-precondiciones-a-los-setters)

2019-11-01 17:23 UTC, Jimenarosello requested changes
Just a few tips! 😃 Also, remember that it's a good practice to isolate response messages as constants :)

2019-11-01 17:23 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +		Preconditions.checkArgument(pages < 0, "Quantity of pages cannot be negative or zero");
Careful here, it should be `pages >= 0` 😃

2019-11-01 17:23 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +		Preconditions.checkNotNull(isbn);
Maybe you could add your own custom message :)

2019-11-01 17:23 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
>  		return (List<Users>) Collections.unmodifiableCollection(this.users);
I think you will need to switch `unmodifiableCollection` for `unmodifiableList`

2019-11-13 12:49 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +		if (this.users.contains(user))
You can also use Preconditions here 😄 just a note for the future :)

2019-11-13 12:50 UTC, Jimenarosello approved these changes
Nice job 😊

2019-11-19 14:21 UTC, rodrigofranc approved these changes

2019-11-21 13:41 UTC, merged