Add Book Model
wolox-training/jc-java pull request #5
Opened 2019-10-16 14:19 UTC by Casanova569

**Summary**
The card is considered approved if after performing the class mapping, the application lifts and responds upon entering the url "localhost:8081".

**Trello Card**
[Crear modelo de Book](https://trello.com/c/LsJDu0XT/14-crear-modelo-de-book)

2019-10-18 18:01 UTC, rodrigofranc requested changes

2019-10-18 18:01 UTC, rodrigofranc commented on src/main/java/wolox/training/models/Book.java
> +public class Book {
All attributes should be lower case

2019-10-18 18:01 UTC, rodrigofranc commented on src/main/java/wolox/training/models/Book.java
> +	@Id
Getter method for this is missing

2019-10-18 18:07 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +	@Column()
Just as a comment, the parenthesis aren't necessary here :)

2019-10-18 18:07 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +	}
Maybe you could add a getter (however, not a setter) for the book id. 
Another thing you could consider is using Lombok for the getters and setters, to help with writing the class :) just a suggestion for the future. See [this link](http://www.javabyexamples.com/lombok-data-and-value-for-fast-pojos/) as reference

2019-10-18 18:08 UTC, Jimenarosello requested changes

2019-10-18 18:08 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +	public Book(String genre, String author, String image, String title, String subtitle,
I think you could add `final` to each parameter

2019-10-21 21:58 UTC, rodrigofranc approved these changes

2019-10-23 15:32 UTC, Jimenarosello approved these changes
😃

2019-10-23 15:33 UTC, merged