Add Books Repository
wolox-training/jc-java pull request #6
Opened 2019-10-16 18:21 UTC by Casanova569

**Summary**
The card is considered approved if you can create a new repository for books and it has everything requested (define a method to search for a book by author and only return one result), compiles and the application lifts without errors.

**Trello Card**
[Crear un Repositorio de Books](https://trello.com/c/VlOrYXx4/15-crear-un-repositorio-de-books)

2019-10-18 18:14 UTC, Jimenarosello requested changes
Looks good! Just a few suggestions 😄

2019-10-18 18:14 UTC, Jimenarosello commented on src/main/java/wolox/training/repositories/BookRepository.java
> +	public Book findBookByAuthor(String author);
this method should return an Optional<Book> to avoid nullchecks whenever possible :)

2019-10-18 18:14 UTC, Jimenarosello commented on src/main/java/wolox/training/repositories/BookRepository.java
> +public interface BookRepository extends Repository {
You could extend from CrudRepository<Book, Integer>, which returns Optional<Book> in the methods :)

2019-10-23 15:26 UTC, rodrigofranc submitted a review, later dismissed

2019-10-23 15:34 UTC, Jimenarosello requested changes
Just one thing and it should be ready :)

2019-10-23 15:34 UTC, Jimenarosello commented on src/main/java/wolox/training/repositories/BookRepository.java
> +	public Book findByAuthor(String author);
Remember to return Optional<Book> :)

2019-10-30 17:03 UTC, Jimenarosello approved these changes
😄👍

2019-10-31 13:48 UTC, rodrigofranc approved these changes

2019-10-31 14:05 UTC, merged